### ISSUE TITLE
Package not updated on NPM since 9 month

### ISSUE THREAD

**Issue by eneufeld** [eclipse-theia/theia-cpp-extensions#130]
First of all, thank you for this great package.

**Description**
I would like to consume the newest version of the package, unfortunately the latest version on npm is 9 month old.
The current publish is failing with a timeout as a version needs to be selected: https://github.com/eclipse-theia/theia-cpp-extensions/runs/3568902244

**Additional Information**
https://www.npmjs.com/package/@theia/cpp-debug

**Comment by marcdumais-work** [comment]
Hi @eneufeld ,

@theia/cpp-debug is in transition right now. The way forward that we see is to instead use vscode extension `cdt-gdb-vscode` (available from open-vsx and from Theia extensions view).

The only think missing in there vs @theia/cpp-debug  is the enhanced memory view, which we plan to spin as its own generic Theia extension, that would be usable with any Debug Adapter that implements memory reads/writes, including `cdt-gdb-vscode`.

cc: @vince-fugnitto @colin-grant-work : anything to add?

**Comment by vince-fugnitto** [comment]
> cc: @vince-fugnitto @colin-grant-work : anything to add?

@marcdumais-work right, I just wanted to add that I was planning on making a release (`@theia/cpp-debug`) when we are happy with the new memory-viewer, and a few of the follow-up pull-requests were merged (currently under review).

**Comment by eneufeld** [comment]
Hi @marcdumais-work @vince-fugnitto , 
thank you for your information. I totally see your point here.
I just wanted to consume the newest version which is compatible with the latest Theia version and was wondering that the auto deploy is in place but failing.
Looking forward to the release.

**Comment by marcdumais-work** [comment]
@eneufeld Understood. 

> I was planning on making a release (@theia/cpp-debug) when we are happy with the new memory-viewer, and a few of the follow-up pull-requests were merged (currently under review).

@vince-fugnitto Sounds like a plan

**Comment by JonasHelming** [comment]
@vince-fugnitto Great, another release before any further restructuring would be great!

**Comment by JonasHelming** [comment]
@vince-fugnitto Could you give us an ETA for the updated NPM release? The reason I ask is that we prepare a demo for EclipseCon and we need to decide whether we wait for this (which would simplify things) or do some work around.
So no pushing, but just asking for an estimation :-)
Thanks!

**Comment by vince-fugnitto** [comment]
@JonasHelming a new version of `@theia/cpp-debug` was published [v1.18.0](https://www.npmjs.com/package/@theia/cpp-debug), which uses `1.17.2` of theia. It is possible that the repo will need to be updated to use `latest` as a version range when we perform subsequent releases so that we don't have so much overhead to release as the framework releases and can target additional ranges.

**Comment by marcdumais-work** [comment]
After discussion with @paul-marechal we decided to make changes. We will unpublish the package above and instead publish `1.17.2`. A `1.18.0` version will follow, after that release in the main Theia repo.

**Comment by marcdumais-work** [comment]
Seems to work - thanks @vince-fugnitto for the release
![image](https://user-images.githubusercontent.com/25749063/135348282-da14e3a7-0f66-4ed8-8618-ea0eefddb88a.png)

**Comment by marcdumais-work** [comment]
@eneufeld the scheme we came-up with, is that one needs to match the `@theia/cpp-debug` package version to the version of the Theia framework used, along with it. This means that to use the package we published today, you need to have an application based on Theia `v1.17.2`, which is the latest Theia framework available today.

**Comment by eneufeld** [comment]
@marcdumais-work @vince-fugnitto  Thank you for the release, I tested it and it works like a charm!

I'm looking forward to your future refactoring, keep up the great work!

**Comment by JonasHelming** [comment]
Thank you very much!
