### ISSUE TITLE
Please consider renaming to: theia-example-app-using-cpp

### ISSUE THREAD

**Issue by frank-dspeed** [eclipse-theia/theia-cpp-extensions#151]
**Description**
Please consider renaming to: theia-example-app-using-cpp

**Additional Information**
It took me relativ long to audit what this is and since the c++ extension is deprecated rename is the only thing that makes sense to me thanks in advance. Also i would want to suggest to name it maybe only : example-app-using-cpp so drop the theia- in the repo name as it is already there because of the org. People forking and Handling large repos will anyway use full url org name as reference if they need it.

**Comment by vince-fugnitto** [comment]
The rename is not something we are looking to do, the repo is about C/C++ extensions such as `@theia/cpp-debug` it is not an example application.

**Comment by marcdumais-work** [comment]
Hi @frank-dspeed,

In case you are looking, we do have a more official C/C++ example application: https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint

We might eventually move `@theia/cpp-debug` under the same org

**Comment by marcdumais-work** [comment]
Hi @frank-dspeed,

In case you are looking, we have a more official C/C++ example application: https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint

**Comment by frank-dspeed** [comment]
@marcdumais-work that is a good idea it would help i have invented a total new interface method for browsers and ramping up a complete rework of theia via codeMods that why i found that i am visiting all existing code so that the automation does not do something wrong and this repo was not easy to categorize via the automation. Hope that helps.  

i am not blocked by it but when some one like me needs so much time to find out what it does then a person with less then 5 years of experience is in trouble i am 100% sure about that.

at present theia is interfacing browsers and electron from the inside i created a interface for it so that the theia agent can send the data from the outside to the browser page via OS methods so we can drop stuff like Electron hardcoding.
