### ISSUE TITLE
Rename repository?

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia-cpp-extensions#31]
I know that renaming repositories is often a problem, but GitHub makes it relatively nice to do since [it will redirect the old URLs to the new one for quite some time](https://github.blog/2013-05-16-repository-redirects-are-here/).

Reason is that this repository seems to have been created to host the `@theia/cpp` extension, currently located in Theia's main mono-repository.

For people not familiar with the JS world, mono-repositories are repositories hosting several packages at once, it avoids having to work on linked packages from different and individual git repositories.

The issue here is that this repository is named `theia-cpp-extension` (singular) but is already a mono-repository containing 2 packages/extensions, without counting the `@theia/cpp` package/extension which is planned to move sometime later.

My suggestion is to rename the repository `theia-cpp-extensions` (plural). It may sound like I'm making a lot of noise for a silly singular vs plural question, but I really prefer removing the confusion that could happen due to incoherent naming.

@eclipsewebmaster is this something worth the trouble?

**Comment by marcdumais-work** [comment]
@marechal-p Sounds good to me. I have requested the Foundation creates a new GH org for Theia, `eclipse-theia`, and I thought we could then ask to move this repo there. Then we can request the needed GH applications to be installed/configured (e.g. Travis CI) and validate that they work well.

All this to say: maybe we can ask webmaster to move the repo to the new org and rename it at the same time? 

cc: @thegecko

**Comment by thegecko** [comment]
No concerns

**Comment by vince-fugnitto** [comment]
Can be closed thanks to the org move and rename :)
