### ISSUE TITLE
[CI] add CI, tests for extensions in this repo

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia-cpp-extensions#4]
_Updated:_
- [x] enable CI integration ( travis for linux, windows, macOS )
- [x] add tests ( potential specific UI tests for C/C++ as a bonus 🏅 )

_Original Content_
> We should build, test Theia extensions contained in this repo. We should publish a ```next``` versions on npm, for modified extensions, upon check-in of PRs.

**Comment by vince-fugnitto** [comment]
CI and tests have been added to the repository :)
