### ISSUE TITLE
Update cpp-debug to latest cdt-gdb-vscode release

### ISSUE THREAD

**Issue by dwjbosman** [eclipse-theia/theia-cpp-extensions#46]
Can
theia-cpp-extensions/packages/cpp-debug/package.json 

be updated to use the latest cdt-gdb-vscode release?

https://github.com/theia-ide/cdt-gdb-vscode/releases/tag/v0.0.90-theia.2

**Comment by vince-fugnitto** [comment]
I believe it's being handled by https://github.com/eclipse-theia/theia-cpp-extensions/pull/39

**Comment by dwjbosman** [comment]
Ok
