### ISSUE TITLE
Update version reference of @theia/ext-scripts

### ISSUE THREAD

**Issue by dwjbosman** [eclipse-theia/theia-cpp-extensions#47]
theia-cpp-extensions/packages/cpp-debug/package.json 

contains a line:

"@theia/ext-scripts": "0.9.0"

I'm getting an error during install:

error Couldn't find package "@theia/ext-scripts@0.9.0" required by "@theia/cpp-debug@*" on the "npm" registry.

**Comment by marcdumais-work** [comment]
Closing
