### ISSUE TITLE
[Cortex-Debug] Issues using OpenOCD

### ISSUE THREAD

**Issue by dwjbosman** [eclipse-theia/theia-cpp-extensions#51]
I'm trying to test the cortex-debug extension.

The original VS Code plugin has been updated to V0.2.7. See https://github.com/eclipse-theia/theia-cpp-extensions/pull/50

Also:

1. 
The https://github.com/Marus/cortex-debug/blob/master/package.json file contains many contributions to "Cortex-Debug Configuration". Where are these settings located in Theia?

I'm trying to work with OpenOCD as a gdb server:

2. When I use this

```
"configurations": [
      {
          "name": "Debug Microcontroller",
          "type": "cortex-debug",
          "request": "launch",
          "servertype": "openocd",
          "runToMain": true,
          "executable": "${workspaceFolder}/target/thumbv7m-none-eabi/debug/example-embedded",
          "cwd": "${workspaceRoot}",
          "showDevDebugOutput": true,
          "configFiles": ["/home/dinne/theia-apps/theia-rust-embedded-docker/example-embedded/openocd.cfg"]
          //"target": {"port": "1234", "host": "127.0.0.1"},
          //"program": "${workspaceFolder}/target/thumbv7m-none-eabi/debug/example-embedded"
      }
]
```

The debugging hangs but there is a failure message:
```

Unhandled rejection TypeError: Cannot read property 'forEach' of undefined
    at OpenOCDServerController.serverArguments (/root/theia_rust_app/node_modules/@theia/cortex-debug/download/cortex-debug/extension/out/src/openocd.js:95:29)
    at portastic.find.then (/root/theia_rust_app/node_modules/@theia/cortex-debug/download/cortex-debug/extension/out/src/gdb.js:136:48)
    at tryCatcher (/root/theia_rust_app/node_modules/@theia/cortex-debug/download/cortex-debug/extension/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/root/theia_rust_app/node_modules/@theia/cortex-debug/download/cortex-debug/extension/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/root/theia_rust_app/node_modules/@theia/cortex-debug/download/cortex-debug/extension/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/root/theia_rust_app/node_modules/@theia/cortex-debug/download/cortex-debug/extension/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/root/theia_rust_app/node_modules/@theia/cortex-debug/download/cortex-debug/extension/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/theia_rust_app/node_modules/@theia/cortex-debug/download/cortex-debug/extension/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

When I run openocd from the command line it is no problem. openocd.cfg is available in the workspace dir.

3. When I add the configuration file explicitly:

```
"configurations": [
      {
          "name": "Debug Microcontroller",
          "type": "cortex-debug",
          "request": "launch",
          "servertype": "openocd",
          "runToMain": true,
          "executable": "${workspaceFolder}/target/thumbv7m-none-eabi/debug/example-embedded",
          "cwd": "${workspaceRoot}",
          "showDevDebugOutput": true,
          "configFiles": ["/home/dinne/theia-apps/theia-rust-embedded-docker/example-embedded/openocd.cfg"]
      },
```

The plugin fails after some time with a popup in Theia (Failed to launch OpenOCD GDB Server: Timeout.)
3.1
How can I get more debug output. The plugin starts a separate node process.
3.2.
Where in general are Theia's logfiles located?

**Comment by vince-fugnitto** [comment]
cc @thegecko perhaps you can provide some answers to the questions.

**Comment by thegecko** [comment]
Looks like it's expecting a `serverArguments` array in your configuration. Try passing an empty array. Would also suggest you get it working in VS Code first to ensure the config is correct. We've only used this adapter with pyocd and recently switched away to a different one, so sorry if I can't help any further.

**Comment by vince-fugnitto** [comment]
> Looks like it's expecting a `serverArguments` array in your configuration. Try passing an empty array. Would also suggest you get it working in VS Code first to ensure the config is correct. We've only used this adapter with pyocd and recently switched away to a different one, so sorry if I can't help any further.

@thegecko 
I have a general question regarding the `cortext-debug` extension. 
You mentioned that in the past it used to be used, and that recently you've switched to a different solution. Is the extension still actively supported/maintained or plan to be? I'm wondering it it'll be worthwhile to keep maintaining it or should we in fact clean-up and deprecate it if its no longer the case.

**Comment by thegecko** [comment]
> Is the extension still actively supported/maintained or plan to be?

Not by me/us

> should we in fact clean-up and deprecate?

May be sensible unless another maintainer steps up.

FYI, we now use this adapter:

https://github.com/armmbed/cmsis-debug-adapter

Which uses the core gdb adapter here:

https://github.com/eclipse-cdt/cdt-gdb-adapter

**Comment by vince-fugnitto** [comment]
> > Is the extension still actively supported/maintained or plan to be?
> 
> Not by me/us

👍 

> > should we in fact clean-up and deprecate?
> 
> May be sensible unless another maintainer steps up.

I see you as the original author/contributor :)
Would it cause issues for you to deprecate? @dwjbosman

**Comment by dwjbosman** [comment]
I would still like to get it working. 

I downloaded the package to a local location. So that I could easily add some modificiations. However if I try to install with yarn the "lib" directory is not created and theia build fails. If I install from the npm repo the lib directory inside node_modules/cortext-debug is created. I want to sort this out and test.

The cortext-debug extension for vs code has some interesting graphing features using SWV which I would like to try.

**Comment by vince-fugnitto** [comment]
> The cortext-debug extension for vs code has some interesting graphing features using SWV which I would like to try.

From my knowledge, the VSCode extension can be used without the `cortex-debug` present in this repository. It's exactly the reason I was wondering if we should still keep this extension despite no
support/maintenance plans.

**Comment by dwjbosman** [comment]
> > The cortext-debug extension for vs code has some interesting graphing features using SWV which I would like to try.
> 
> From my knowledge, the VSCode extension can be used without the `cortex-debug` present in this repository. It's exactly the reason I was wondering if we should still keep this extension despite no
> support/maintenance plans.

Hi, I have tried to install the cortex-debug plugin from the vscode repository. This works partly, there is a problem with the plugin. The cortex-debug plugin uses ipv6 which gives problems inside a Docker container. I want to test a fork of cortex-debug which has been patches. However this fork is not published on the vscode marketplace.

Is it possible to install directly from the github repository (https://github.com/haneefdm/cortex-debug) of the plugin in stead of using the marketplace? 

A snippet from my package.json:
```
(
    "scripts": {
        "postinstall": "download-debug-adapters"
    },
    "adapterDir": "plugins",
    "adapters": {
        "vscode-cortex-debug": "https://marus25.gallery.vsassets.io/_apis/public/gallery/publisher/marus25/extension/Cortex-Debug/0.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage"
    },
)
```

**Comment by thegecko** [comment]
> Is it possible to install directly from the github repository

Not AFAIK. You need to host a zipped copy of the compiled adapter.

**Comment by vince-fugnitto** [comment]
I believe it is possible based on the documentation from `npm`:
- https://docs.npmjs.com/files/package.json#urls-as-dependencies
- https://docs.npmjs.com/files/package.json#github-urls

**Comment by thegecko** [comment]
> I believe it is possible

Be aware this will only grab the source, not the compiled adapter.

**Comment by dwjbosman** [comment]
I got the vscode cortex-debug extension working in Docker by enabling ipv6. 

> > The cortext-debug extension for vs code has some interesting graphing features using SWV which I would like to try.
> 
> From my knowledge, the VSCode extension can be used without the `cortex-debug` present in this repository. It's exactly the reason I was wondering if we should still keep this extension despite no
> support/maintenance plans.

I don't require the Theia version anymore.

**Comment by vince-fugnitto** [comment]
Closing in favor of #61
