### ISSUE TITLE
[cpp] Do not send all the cpp settings to clangd

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia-cpp-extensions#71]
According to the following trace, we seem to send all Theia's C++ settings to clangd:

```
root ERROR C/C++: V[09:55:05.495] <<< {
  "jsonrpc": "2.0",
  "method": "workspace/didChangeConfiguration",
  "params": {
    "settings": {
      "cpp": {
        "buildConfigurations": [],
        "clangTidy": false,
        "clangTidyChecks": "",
        "clangdArgs": "-background-index -header-insertion=never -log=verbose",
        "clangdExecutable": "/home/meh/build/llvm-release/bin/clangd",
        "experimentalCommands": false,
        "experimentalCompilationDatabaseMap": false,
        "trace": {
          "server": "off"
        }
      }
    }
  }
}
```

Am not yet sure if it is done this way for all language servers, but we should definitely not send this to clangd.

**Comment by vince-fugnitto** [comment]
I transferred the issue from the main repo following the move of `@theia/cpp` to                      `theia-cpp-extensions`.

**Comment by vince-fugnitto** [comment]
The @theia/cpp extension is deprecated and removed from the repository in favor of consuming vscode extensions (such as vscode-clangd).
