### ISSUE TITLE
[CI] add cron job to test against upstream

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia-cpp-extensions#78]
**Description**

Include a CRON job to test the repository against upstream changes nightly so we can identify and fix potential issues and breaking changes.

**Comment by vince-fugnitto** [comment]
CRON job has been added :smiley:

**Comment by marcdumais-work** [comment]
Looks like it worked. [CI passed](https://travis-ci.com/eclipse-theia/theia-cpp-extensions/builds/138620036) and a `0.14.0-next.b9558cf1` version was published for our two extensions.
