### ISSUE TITLE
Cannot apply @injectable decorator multiple times.

### ISSUE THREAD

**Issue by Briffou** [eclipse-theia/theia-cpp-extensions#96]
**Description**
I'm using the package.json from https://github.com/eclipse-theia/theia-cpp-extensions/blob/master/browser-app/package.json and still have the issue describe in https://github.com/eclipse-theia/theia/issues/3780

![issue](https://user-images.githubusercontent.com/18452695/76762388-9823d900-6767-11ea-85e8-f1c7eaa8a9ca.png)

**How to reproduce:**
Install theia using package.json from this repo (browser-app) 

**Expected behavior**
No error

**Environment**
 - _OS_: Fedora 31
 - _Browser_: Firefox 74.0
 - _Theia Version_:  0.16.0

**Additional information**

**Comment by vince-fugnitto** [comment]
@Briffou I just verified and it worked correctly:

<img width="922" alt="Screen Shot 2020-03-16 at 10 48 03 AM" src="https://user-images.githubusercontent.com/40359487/76770036-ad9f0000-6773-11ea-857e-9f7398df43fc.png">

<img width="1049" alt="Screen Shot 2020-03-16 at 10 49 17 AM" src="https://user-images.githubusercontent.com/40359487/76770157-d7f0bd80-6773-11ea-86d1-8980ca5f097b.png">

**Comment by vince-fugnitto** [comment]
@Briffou do you happen to have an outdated `yarn.lock` present?

**Comment by Briffou** [comment]
It was that, thanks !
